name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - master 

env:
  APPID: ${{ secrets.mule_connected_app_prod_id }}
  APPSECRET: ${{ secrets.mule_connected_app_prod_secret }}
  ENVID: ${{ secrets.prod_client_id  }}
  ENVSECRET: ${{ secrets.prod_client_secret  }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Deploy to Production
      working-directory: ./dev-agent
      run: |
        mvn clean deploy -DmuleDeploy \
         -Dapp.name="dev-agent-prod" \
         -Denvironment="Pord" \
         -Dtarget.env="prod" \
         -Danypoint.psname="Cloudhub-US-East-2"  \
         -Dconnected.app.id="$APPID" \
         -Dconnected.app.secret="$APPSECRET" \
         -Denv.client.id="$ENVID" \
         -Denv.client.secret="$ENVSECRET"
